@startuml
start
:**Выгрузка**.
Нужные страницы из Wookiepedia выгружаются в папку **raw** html-файлами.;
:**Извлечение текста**.
Из каждого выгруженного html-файла извлекается текст и сохраняется текстовым
документом в папку **extracted**.;
:**Очистка текста**.
Каждый текстовый документ очищается от набора различных стоп-слов, заменяются
слова с опечатками. Очищенные и обработанные текстовые документы сохраняются в
папку **knowloedge_base**;
:**Разбиение текста на куски**.
Индексатор проверяет, изменились ли документы, сверяя их контрольные суммы
**md5** c контрольными суммами, сохранёнными во внутренней базе. Новые или
обновлённые документы разбиваются на куски с небольшим перехлёстом. Каждый
кусок сохраняется в SQLITE3. Для каждого обработанного документа сохраняются
сведения о нём и контрольная сумма. Для изменённых документов индексатор
запоминает номера кусков для последующего удаления соответствующих им векторов
из векторного индекса;
split
    :**Векторизация кусков**.
    Для каждого куска с помощью модели эмбеддингов извлекается его вектор
    признаков.;
    :**Сохранение в векторный индекс**.
    Каждый новый вектор сохраняется в векторный индекс.;
split again
    :**Удаление старых векторов**.
    Индексатор удаляет для обновлённых документов их старые векторы из
    векторного индекса.;
end split
split
    :**Сохранение векторного индекса**.
    Используется FAISS;
split again
    :**Сохранение базы данных по документам**.
    Используется SQLITE3;
end split
stop
@endum
